import { FormEvent, useEffect, useMemo, useState } from 'react'
import { categories, Expedition, expeditions, formatPrice } from './data'

const Icon = ({ name }: { name: 'arrow'|'heart'|'close'|'menu'|'copy'|'check' }) => {
  const paths = { arrow:<><path d="M4 12h15"/><path d="m13 5 7 7-7 7"/></>, heart:<path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.9-8.6a5.5 5.5 0 0 0-.1-7.8Z"/>, close:<><path d="m6 6 12 12M18 6 6 18"/></>, menu:<><path d="M3 6h18M3 12h18M3 18h18"/></>, copy:<><rect x="8" y="8" width="12" height="12" rx="1"/><path d="M16 8V5a1 1 0 0 0-1-1H5a1 1 0 0 0-1 1v10a1 1 0 0 0 1 1h3"/></>, check:<path d="m5 12 4 4L19 6"/> }
  return <svg aria-hidden="true" viewBox="0 0 24 24">{paths[name]}</svg>
}

function App() {
  const [filter, setFilter] = useState<string>('все')
  const [selected, setSelected] = useState<Expedition | null>(null)
  const [mapItem, setMapItem] = useState(expeditions[0])
  const [favourites, setFavourites] = useState<string[]>(() => JSON.parse(localStorage.getItem('orbis-favourites') || '[]'))
  const [menuOpen, setMenuOpen] = useState(false)
  const [progress, setProgress] = useState(0)
  const [quizStep, setQuizStep] = useState(0)
  const [answers, setAnswers] = useState<string[]>([])
  const [sent, setSent] = useState(false)
  const visible = useMemo(() => filter === 'все' ? expeditions : expeditions.filter(x => x.categories.includes(filter as never)), [filter])
  const suggestions = useMemo(() => {
    const q = answers.join(' ')
    return [...expeditions].sort((a,b) => score(b,q)-score(a,q)).slice(0,3)
  }, [answers])
  useEffect(() => { localStorage.setItem('orbis-favourites', JSON.stringify(favourites)) }, [favourites])
  useEffect(() => { const f=()=>setProgress(Math.min(100,Math.round(scrollY/(document.documentElement.scrollHeight-innerHeight)*100)||0)); addEventListener('scroll',f,{passive:true}); f(); return()=>removeEventListener('scroll',f) }, [])
  const toggleFav=(id:string)=>setFavourites(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id])
  const scrollTo=(id:string)=>{ document.getElementById(id)?.scrollIntoView({behavior:'smooth'}); setMenuOpen(false) }
  const choose=(value:string)=>{ setAnswers(a=>[...a,value]); setQuizStep(s=>s+1) }
  return <>
    <div className="progress" style={{transform:`scaleX(${progress/100})`}} />
    <header className="header"><button className="brand" onClick={()=>scrollTo('top')} aria-label="ORBIS, в начало">ORBIS<span>•</span></button><nav className={menuOpen?'nav open':'nav'} aria-label="Основная навигация"><button onClick={()=>scrollTo('routes')}>Экспедиции</button><button onClick={()=>scrollTo('atlas')}>Атлас</button><button onClick={()=>scrollTo('safety')}>Подход</button><button onClick={()=>scrollTo('contact')}>Связаться</button></nav><button className="menu-btn" onClick={()=>setMenuOpen(!menuOpen)} aria-expanded={menuOpen} aria-label="Меню"><Icon name={menuOpen?'close':'menu'}/></button></header>
    <main id="main">
      <section className="hero" id="top"><div className="hero-image"/><div className="hero-overlay"/><div className="hero-grid"/><div className="hero-aurora"/><div className="orbital-object" aria-hidden="true"><i/><i/><i/><b>O</b></div><div className="hero-content"><p className="eyebrow light">01 — частные экспедиции · 2026</p><h1>За пределами<br/><em>очевидного.</em></h1><p className="hero-lead">Маршруты в места, где карта становится личной историей. Продумано до детали. Открыто для неожиданного.</p><div className="hero-actions"><button className="button primary" onClick={()=>scrollTo('finder')}>Найти своё приключение <Icon name="arrow"/></button><button className="text-button light" onClick={()=>scrollTo('routes')}>Исследовать маршруты <span>↓</span></button></div></div><div className="hero-meta"><span>64°08′ N · 18°23′ W</span><span>ORBIS / FIELD NOTES</span></div><button className="scroll-cue" onClick={()=>scrollTo('manifest')} aria-label="Прокрутить к манифесту"><i/> листайте, чтобы войти</button></section>

      <section className="manifest section" id="manifest"><p className="eyebrow">02 — Манифест</p><div className="manifest-layout"><p className="display-copy">Самые сильные места планеты существуют не только на фотографиях.</p><div><p>ORBIS создаёт путь к ним — с людьми, которые знают местность, с планом, который выдерживает перемену погоды, и с запасом времени, чтобы по-настоящему оказаться внутри ландшафта.</p><a href="#safety">Как мы работаем <Icon name="arrow"/></a></div></div><div className="manifest-mark">O<span>∞</span></div></section>

      <section className="routes section dark" id="routes"><div className="section-head"><div><p className="eyebrow light">03 — Коллекция маршрутов</p><h2>Не пункты назначения.<br/><em>Направления мысли.</em></h2></div><p>Небольшие группы, редкие окна сезона и маршруты, собранные командой на месте.</p></div><div className="filters" role="group" aria-label="Фильтры маршрутов"><button className={filter==='все'?'active':''} onClick={()=>setFilter('все')}>все <small>{expeditions.length}</small></button>{categories.map(c=><button key={c} className={filter===c?'active':''} onClick={()=>setFilter(c)}>{c}</button>)}</div>
        {visible.length ? <div className="route-grid">{visible.map((item,i)=><article className={`route-card c${i%5}`} key={item.id}><div className="card-media"><img src={item.image} alt={item.alt} loading="lazy"/><div className="card-shade"/><span className="route-no">{item.no}</span><button className={favourites.includes(item.id)?'fav chosen':'fav'} onClick={()=>toggleFav(item.id)} aria-label="Добавить в избранное"><Icon name="heart"/></button><div className="card-title"><p>{item.place}</p><h3>{item.title}</h3></div><button className="card-open" onClick={()=>setSelected(item)}>Смотреть маршрут <Icon name="arrow"/></button></div><div className="card-info"><p>{item.description}</p><dl><div><dt>Длительность</dt><dd>{item.duration} дней</dd></div><div><dt>Группа</dt><dd>{item.group}</dd></div><div><dt>От</dt><dd>{formatPrice(item.price)}</dd></div></dl></div></article>)}</div> : <div className="empty"><p>В этой части атласа пока тихо.</p><button className="button outline" onClick={()=>setFilter('все')}>Сбросить фильтр</button></div>}
      </section>

      <section className="atlas section" id="atlas"><div className="section-head"><div><p className="eyebrow">04 — Атлас ORBIS</p><h2>Выберите<br/><em>точку входа.</em></h2></div><p>Поставьте палец на карту — и маршрут покажет, где начинается ваша следующая история.</p></div><div className="atlas-frame"><img className="map-image" src="/assets/world-map-copper.webp" alt="Стилизованная медная карта мира"/>{expeditions.map(e=><button key={e.id} className={`map-point ${mapItem.id===e.id?'current':''}`} style={{left:`${e.map.x}%`,top:`${e.map.y}%`}} onClick={()=>setMapItem(e)} aria-label={e.title}><i/></button>)}<div className="map-caption"><p className="eyebrow">Экспедиция {mapItem.no}</p><h3>{mapItem.title}</h3><p>{mapItem.place} · {mapItem.duration} дней</p><button className="text-button" onClick={()=>setSelected(mapItem)}>Открыть карточку <Icon name="arrow"/></button></div><p className="map-legend">нажмите на метку<br/>маршрута</p></div></section>

      <section className="journey dark"><div className="journey-photo"/><div className="journey-content"><p className="eyebrow light">05 — Как читается путь</p><h2>Одна история.<br/><em>Пять глав.</em></h2><ol>{['Знакомство и подготовка','Прибытие в ритм места','Путь к удалённой локации','Главное открытие','Возвращение с новым масштабом'].map((t,i)=><li key={t}><span>0{i+1}</span><div><h3>{t}</h3><p>{['Собираем группу, проводим брифинг, проверяем снаряжение и отвечаем на вопросы.', 'Встречаем в точке старта. Акклиматизация — часть маршрута, а не формальность.', 'Меняем транспорт, темп и оптику. Команда постоянно считывает условия.', 'Не «галочка» в списке, а достаточно времени, чтобы место раскрылось.', 'Продуманная логистика домой и материалы из полевого дневника.'][i]}</p></div></li>)}</ol></div></section>

      <section className="finder section" id="finder"><div className="finder-intro"><p className="eyebrow">06 — Навигатор</p><h2>Не знаете,<br/><em>с чего начать?</em></h2><p>Четыре коротких вопроса помогут найти подходящее направление. Всё работает в браузере — ответы никуда не отправляются.</p></div><div className="quiz">{quizStep<4 ? <><p className="quiz-count">0{quizStep+1} / 04</p><h3>{['Какой ландшафт сейчас зовёт?','Какой темп вам ближе?','Сколько времени готовы отдать пути?','В какое время года хотите уехать?'][quizStep]}</h3><div className="quiz-options">{[['лёд','океан','пустыня','джунгли','горы'],['Мягкий','Умеренный','Высокий'],['6','8','12'],['зима','весна','лето','осень']][quizStep].map(v=><button key={v} onClick={()=>choose(v)}>{v}<Icon name="arrow"/></button>)}</div></> : <><p className="quiz-count">ваш маршрутный лист</p><h3>Начните<br/>с этих линий.</h3><div className="quiz-results">{suggestions.map(x=><button key={x.id} onClick={()=>setSelected(x)}><span>{x.no}</span><b>{x.title}</b><small>{x.place}</small><Icon name="arrow"/></button>)}</div><button className="restart" onClick={()=>{setAnswers([]);setQuizStep(0)}}>Пройти заново</button></>}</div></section>

      <section className="safety section dark" id="safety"><p className="eyebrow light">07 — Свобода, на которую можно опереться</p><div className="safety-layout"><h2>Приключение — это<br/><em>не отсутствие плана.</em></h2><div className="safety-list">{[['01','Люди маршрута','Руководитель, медик и локальные эксперты подбираются под конкретную среду.'],['02','Разведка до старта','Проверяем дороги, точки связи, воду и альтернативные ночёвки.'],['03','Связь и навигация','Спутниковая связь, трекинг группы и офлайн-навигация работают параллельно.'],['04','Резервные сценарии','Погода или рельеф меняются — поэтому у каждого дня есть безопасная вариация.'],['05','Малая группа','Не более восьми гостей: это бережнее к месту и внимательнее к каждому.']].map(x=><article key={x[0]}><span>{x[0]}</span><div><h3>{x[1]}</h3><p>{x[2]}</p></div></article>)}</div></div></section>

      <section className="team section"><p className="eyebrow">08 — Люди за горизонтом</p><div className="team-head"><h2>Опыт — это<br/><em>умение быть рядом.</em></h2><p>Четыре роли, которые превращают сложную логистику в спокойное присутствие в настоящем моменте.</p></div><div className="team-grid">{[['Алексей Руденко','Руководитель экспедиций','15 лет ведёт группы по льду и вулканическим плато. Любит тишину перед выходом.'],['Лейла Алиева','Врач экспедиций','Отвечает за медицинский контур и за ту уверенность, с которой можно идти дальше.'],['Марк Тана','Локальный проводник','Родился у подножия Кинабалу. Читает лес по запаху дождя и следам на тропе.'],['Софья Ветрова','Координатор маршрутов','Соединяет разрешения, погоду, транспорт и тот самый тёплый чай в точке встречи.']].map((x,i)=><article className={`person p${i}`} key={x[0]}><div className="portrait"><span>{String(i+1).padStart(2,'0')}</span></div><p>{x[1]}</p><h3>{x[0]}</h3><small>{x[2]}</small></article>)}</div></section>

      <section className="proof dark"><div className="numbers"><div><b>48</b><span>экспедиций<br/>в атласе</span></div><div><b>31</b><span>страна<br/>наших маршрутов</span></div><div><b>6.7</b><span>гостей — средняя<br/>группа</span></div><div><b>74</b><span>локальных<br/>эксперта</span></div></div><p className="disclaimer">Показатели и персонажи на этой странице — демонстрационный контент концепта для портфолио.</p></section>

      <section className="notes section"><p className="eyebrow">09 — Из полевых дневников</p><div className="notes-grid">{[['«На третий день я перестала фотографировать. Хотелось просто смотреть, как ледник дышит.»','Елена · Гренландия'],['«Здесь не было ни одной лишней детали: ни в маршруте, ни в тишине вокруг лагеря.»','Никита · Намибия'],['«Дождь изменил план — и именно поэтому мы увидели водопад без единого человека.»','Алина · Борнео']].map((x,i)=><article className={`note n${i}`} key={x[1]}><span>FIELD NOTE / {String(i+1).padStart(2,'0')}</span><blockquote>{x[0]}</blockquote><cite>{x[1]}</cite></article>)}</div></section>

      <section className="contact" id="contact"><div className="contact-image"/><div className="contact-shade"/><div className="contact-content"><p className="eyebrow light">10 — Первый шаг</p><h2>У вашей истории<br/><em>уже есть начало.</em></h2><p>Оставьте ориентир — мы покажем несколько маршрутов, которые стоит рассмотреть.</p>{sent?<div className="form-success"><Icon name="check"/><div><b>Сообщение принято.</b><p>Это демонстрационный интерфейс: данные никуда не отправлялись.</p></div></div>:<form onSubmit={(e:FormEvent)=>{e.preventDefault();setSent(true)}}><label>Ваше имя<input required name="name" placeholder="Как к вам обращаться?"/></label><label>Способ связи<input required name="contact" placeholder="Email или телефон"/></label><label>Интересующее направление<select required defaultValue=""><option value="" disabled>Выберите направление</option>{expeditions.map(x=><option value={x.id} key={x.id}>{x.title}</option>)}</select></label><button className="button primary" type="submit">Отправить ориентир <Icon name="arrow"/></button></form>}</div></section>
    </main>
    <footer><div className="footer-brand">ORBIS<span>•</span></div><p>Экспедиции за пределы очевидного.</p><div className="footer-links"><a href="#top">Instagram ↗</a><a href="#top">Telegram ↗</a><a href="mailto:hello@orbis.example">hello@orbis.example</a></div><small>© 2026 ORBIS. Концепт для портфолио.</small></footer>
    {selected&&<div className="modal-backdrop" role="presentation" onMouseDown={()=>setSelected(null)}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title" onMouseDown={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setSelected(null)} aria-label="Закрыть"><Icon name="close"/></button><img src={selected.image} alt={selected.alt}/><div className="modal-copy"><p className="eyebrow">Маршрут {selected.no} · {selected.place}</p><h2 id="modal-title">{selected.title}</h2><p>{selected.longDescription}</p><div className="modal-details"><span>{selected.duration} дней</span><span>{selected.activity}</span><span>{selected.group}</span><span>{formatPrice(selected.price)}</span></div><ul>{selected.highlights.map(x=><li key={x}>{x}</li>)}</ul><button className="copy-link" onClick={()=>navigator.clipboard?.writeText(`${location.href}#${selected.id}`)}><Icon name="copy"/> Скопировать ссылку</button></div></section></div>}
  </>
}
function score(e: Expedition, q:string){return e.categories.reduce((s,c)=>s+(q.includes(c)?3:0),0)+(q.includes(e.activity)?2:0)+(q.includes(String(e.duration))?1:0)+(q.includes(e.seasonKey)?1:0)}
export default App
